# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-03 14:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coder', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='text',
            new_name='news_text',
        ),
    ]
