# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-04 09:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coder', '0004_auto_20170104_1404'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
